[enhancemnt] 添加贡献指南
sjtug/SJTUThesis pull request #282
Opened 2018-01-12 05:50 UTC by gaocegege

我们需要积极的社区 :-)

Signed-off-by: Ce Gao <ce.gao@outlook.com>

2018-01-12 05:59 UTC, at15 commented on README.md
>  * [在水源 BBS TeX_LaTeX 版发帖](https://bbs.sjtu.edu.cn/bbsdoc?board=TeX_LaTeX)
还有人会去水源 bbs 看么? ....

2018-01-12 05:59 UTC, gaocegege commented on README.md
>  * [在水源 BBS TeX_LaTeX 版发帖](https://bbs.sjtu.edu.cn/bbsdoc?board=TeX_LaTeX)
会, 好多人....

2018-01-12 06:02 UTC, at15 requested changes
我觉得现在 README 好像有点长(可能可以考虑用 summary 来折叠一下) .... 以及貌似没有 FAQ/wiki 的链接?

2018-01-12 06:16 UTC, gaocegege commented
@at15 折叠指的是什么, 我重新修改了一下, 把本地编译完全放在了 wiki 中去做

2018-01-12 07:07 UTC, at15 commented
@gaocegege FYI https://github.com/dear-github/dear-github/issues/166

2018-01-12 07:15 UTC, gaocegege commented
@at15 太复杂了....不想写 HTML

2018-01-12 07:16 UTC, at15 commented
@gaocegege 只是在外面套一层啊.... (是有点烦，所以我才不写 /w\)

2018-01-12 07:17 UTC, at15 approved these changes
LGTM

2018-01-13 11:10 UTC, AlexaraWu approved these changes

2018-01-14 01:31 UTC, merged