完善本科的标题、专业过长以及研究生专业过长问题
sjtug/SJTUThesis pull request #370
Opened 2018-10-10 08:41 UTC by bubifengyun

2018-10-10 08:48 UTC, bubifengyun commented
## 本科的
![_ _20181010163632](https://user-images.githubusercontent.com/4437214/46724241-3165da80-ccac-11e8-8a53-0fb9d0475fba.png)
![_ _20181010163756](https://user-images.githubusercontent.com/4437214/46724242-31fe7100-ccac-11e8-9862-72185fe7ca71.png)

## 研究生的

![sjtu-upload](https://user-images.githubusercontent.com/4437214/46724300-47739b00-ccac-11e8-8e8c-dc3a4a9ef3b4.png)
![sjtu-short](https://user-images.githubusercontent.com/4437214/46724303-47739b00-ccac-11e8-8243-fa563c2499c2.png)

2018-10-10 08:49 UTC, bubifengyun commented
均为英文双分号`;;`表示换行。

2018-10-10 09:03 UTC, gaocegege commented
LGTM

Thanks for your contribution!

2018-10-10 16:31 UTC, AlexaraWu approved these changes

2018-10-10 17:29 UTC, AlexaraWu requested changes
这个想法不错，但是其他用到标题的地方要兼顾一下。

<img width="792" alt="screen shot 2018-10-11 at 01 25 43" src="https://user-images.githubusercontent.com/15205102/46754473-21261d80-ccf5-11e8-92a7-8f955610fa27.png">

2018-10-11 02:32 UTC, bubifengyun commented
嗯嗯，注意到这个问题了。试了好久没有解决，那就换一个折衷方案吧。把两个`;;`换成`\null\null`表示换行。这样就不显示了。如果谁遇到特殊的标题，需要输入`\null\null`，他自己修改为`\null\null\null`就可以了。

2018-10-11 02:47 UTC, bubifengyun commented
看来多虑了，用一个`\null`就足够了。因为`\null`不太可能出现在标题和专业中，他们都是不显示的。

2018-10-22 03:29 UTC, gaocegege commented
/assign @AlexaraWu

2018-10-22 03:29 UTC, gaocegege commented
/assign @AlexaraWu

2018-10-22 03:30 UTC, gaocegege commented
/assign @AlexaraWu

2018-10-22 03:30 UTC, gaocegege commented
/assign @AlexaraWu

2018-10-22 05:30 UTC, AlexaraWu approved these changes

2018-10-22 05:32 UTC, AlexaraWu approved these changes

2018-10-22 06:27 UTC, AlexaraWu approved these changes

2018-10-22 06:27 UTC, AlexaraWu approved these changes

2018-10-22 06:28 UTC, AlexaraWu approved these changes

2018-10-24 03:08 UTC, merged