try match latest template
sjtug/SJTUThesis pull request #622
Opened 2021-05-17 13:29 UTC by skyzh

Fix #583, Fix #620, Fix #621

2021-05-17 13:30 UTC, skyzh commented
主要的修改包括：原创页面默认显示论文名，Logo 改为红色。

2021-05-18 10:11 UTC, AlexaraWu commented
Word 模板的英文校名实际上不符合学校的标准字规范，我觉得这部分不应该参照 Word 模板。

https://vi.sjtu.edu.cn/index.php/articles/base/2

2021-05-18 11:33 UTC, skyzh commented
同意，晚点 revert（

2021-05-18 13:11 UTC, skyzh commented
> Word 模板的英文校名实际上不符合学校的标准字规范，我觉得这部分不应该参照 Word 模板。
> 
> https://vi.sjtu.edu.cn/index.php/articles/base/2

这一部分的修改已经去掉了（

2021-05-18 13:41 UTC, AlexaraWu requested changes

2021-05-18 13:41 UTC, AlexaraWu commented on texmf/tex/latex/sjtuthesis/sjtuthesis-undergraduate.ltx
> +    {\zihao{-2}\MakeUppercase\sjtu@name@school@en\par}
这里的英文校名多余了

2021-05-18 13:41 UTC, AlexaraWu commented on texmf/tex/latex/sjtuthesis/sjtuthesis.cls
> +      acknowledgements  = {谢\hspace{\ccwd}辞},
我们做的是通用模板，本科不一样的自带 可以放在对应的 ltx 文件里

2021-05-18 13:41 UTC, AlexaraWu commented on sjtusetup.tex
> +    title-logo-color = red
这里把 cls 里选项的初始值改成 red 吧，就不要在这里显式地改了

2021-05-18 14:36 UTC, AlexaraWu approved these changes

2021-05-18 14:38 UTC, merged