feat: add `abstract` environment
sjtug/SJTUThesis pull request #708
Opened 2021-09-08 13:43 UTC by skyzh

目前本科生用 `ctexbook` 自带 `abstract` 环境，研究生用 `ctexrep` 没有 `abstract` 环境，所以在 `pg` 情况下自定义了一个 `abstract`. 这个地方是不是要做一些统一（

这个 PR 并不 work，看起来 LaTeX3 的变量自带一个方括号？

<img width="668" alt="image" src="https://user-images.githubusercontent.com/4198311/132520570-c623a126-c154-4034-bb8a-137589bd0e98.png">

2021-09-08 13:44 UTC, skyzh commented
另外 l3build 的 sample 也带上了所有的排列组合，`make build-dev` 即可一键生成（

2021-09-08 13:57 UTC, skyzh commented
以及每一轮编译都会

```
kpathsea: Running mktexmf SimSun
457

458
! I can't find file `SimSun'.
459
<*> ...ljfour; mag:=1; ; nonstopmode; input SimSun
460
                                                  
461
Please type another input file name
462
! Emergency stop.
463
<*> ...ljfour; mag:=1; ; nonstopmode; input SimSun
```

看起来默认的字体配置总是包含 Simsun？

2021-09-09 01:25 UTC, AlexaraWu commented
`\chapter*` 不接受可选参数，和 `\chapter` 是不一样的。

2021-09-09 10:07 UTC, AlexaraWu requested changes
我在 767fcca 里加了摘要环境。

2021-09-09 10:09 UTC, skyzh commented
> 我在 [767fcca](https://github.com/sjtug/SJTUThesis/commit/767fcca98e5f19a85b11f5d919bb81dff89805bf) 里加了摘要环境。

成功！

2021-09-09 10:09 UTC, closed without merging